---
- set_fact:
    monit_version: "5.20.0"

- name: Fetch monit binary
  unarchive:
    src: "https://mmonit.com/monit/dist/binary/{{ monit_version }}/monit-{{ monit_version }}-linux-x64.tar.gz"
    dest: /tmp/
    remote_src: yes
    creates: /tmp/monit-{{ monit_version }}/bin/monit

- name: Copy monit binary to /usr/bin
  copy:
    src: /tmp/monit-{{ monit_version }}/bin/monit
    remote_src: yes
    dest: /usr/bin/monit
    owner: root
    group: root
    mode: 0755

- name: Install monit Upstart conf file
  copy:
    src: monit-upstart.conf
    dest: /etc/init/monit.conf
  when: ansible_service_mgr is undefined or ansible_service_mgr != "systemd"
  notify:
  - restart monit

- name: Install monit Systemd service file
  copy:
    src: monit-systemd.service
    dest: /etc/systemd/system/monit.service
    mode: 0644
  when: ansible_service_mgr is defined and ansible_service_mgr == "systemd"
  notify:
  - restart monit

- name: Create custom monitrc folder
  file:
    path: /etc/monit/monitrc.d
    owner: root
    group: root
    state: directory

- name: Set monit master config file
  template:
    src: monitrc
    dest: "/etc/monit/monitrc"
    mode: 0700

- name: Copy monit configuration for services
  copy:
    src: "{{ item }}"
    dest: "/etc/monit/monitrc.d/{{ item }}"
    mode: 0700
  with_items:
  - fail2ban
  - mongodb
  - nginx
  - system
  - docker

- name: Template uwsgi monit configuration file
  template:
    src: uwsgi
    dest: "/etc/monit/monitrc.d/uwsgi{{ item }}"
    mode: 0700
  with_sequence: count={{ uwsgi_n }}

- name: reload monit config
  shell: monit reload -c /etc/monit/monitrc

- name: Ensure monit is started and enabled on boot (systemd)
  service:
    name: monit
    state: started
    enabled: yes

