# Base app name:
echaloasuerte_app_name:     "echaloasuerte"

# Folder structure
echaloasuerte_root:           "/var/www/{{ echaloasuerte_app_name }}"
echaloasuerte_app:            "{{ echaloasuerte_root }}/web-app"
echaloasuerte_venv:           "{{ echaloasuerte_root }}/venv"
echaloasuerte_static:         "{{ echaloasuerte_root }}/static"
echaloasuerte_logs:           "/var/log/{{ echaloasuerte_app_name }}"

# Branch to deploy
echaloasuerte_git_branch: "master"
