# Base app name:
echaloasuerte_3_app_name:     "echaloasuerte-3"

# Folder structure
echaloasuerte_3_root:         "/var/www/{{ echaloasuerte_3_app_name }}"
echaloasuerte_3_app:          "{{ echaloasuerte_3_root }}/web-app"
echaloasuerte_3_front:        "{{ echaloasuerte_3_root }}/front"
echaloasuerte_3_html:         "{{ echaloasuerte_3_root }}/html"
echaloasuerte_3_venv:         "{{ echaloasuerte_3_root }}/venv"
echaloasuerte_3_logs:         "/var/log/{{ echaloasuerte_3_app_name }}"

# Django settings file to use
echaloasuerte_3_app_settings: "eas.settings.dev"

# Wsgi file location
echaloasuerte_3_app_wsgi: "eas/wsgi.py"

# Version to deploy
echaloasuerte_3_git_branch: "master"

# NPM build config to use
echaloasuerte_3_npm_config: ":dev"

echaloasuerte_3_domains:
  - "beta.echaloasuerte.com"
  - "beta.chooserandom.com"
  - "dev.woreep.com"
  - "beta-dev.echaloasuerte.com"
  - "beta-dev.chooserandom.com"

# Number of docker swarm replicas
echaloasuerte_3_replicas: 1
