- name: restart monit
  service:
    name: monit
    state: restarted
  when: TRAVIS_DEPLOYMENT is not defined

- name: restart filebeat
  service:
    name: filebeat
    state: restarted

- name: restart metricbeat
  service:
    name: metricbeat
    state: restarted
